### PR TITLE
Validate graphql SDL before deploy closes #104

### LINKED ISSUE #104: Validate GraphQL schema before deploying
I ran into an issue where I was using input types in my output types (obviously wrong) but I did not figure this out until I had pasted my schema into the appsync schema section in the console.

It appears as though if the schema is invalid the cloudformation update will simply proceed without updating the schema. There is an argument this is a bug in AWS but it would be nice if this lib would validate the graphql schema prior to upload to prevent this issue.

Can take a stab at this if agreed it's worthwhile.

### PR DESCRIPTION
**Pull request by lightsofapollo**

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -29,6 +30,7 @@ class ServerlessAppsyncPlugin {
         + `is no longer supported. See ${MIGRATION_DOCS} for more information`);
     };
     this.hooks = {
+      'before:deploy:initialize': () => this.validateSchema(),
```
Comment (lightsofapollo) [inline index.js]: I frequently deploy my appsync application so I wanted this validation to happen as quickly as possible.
